# name: Test and Deploy API

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     # 자체 호스팅 러너를 사용하도록 설정
#     runs-on: [self-hosted, Linux, X64]

#     steps:
#     # 1. 저장소 체크아웃
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     # 2. Python 종속성 설치 및 테스트 실행
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.10.11

#     - name: Install dependencies and run tests
#       run: |
#         pip install poetry
#         poetry install --no-root
#         poetry run pytest

#     # 3. Docker 로그인
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     # 4. Docker 이미지 빌드 (GPU 지원)
#     - name: Build Docker Image
#       run: |
#         docker build --build-arg BASE_IMAGE=nvidia/cuda:12.1.1-base-ubuntu20.04 -t ntw0403/sweetsuit:1.0 .

#     # 5. Docker 이미지 푸시
#     - name: Push Docker Image
#       run: |
#         docker push ntw0403/sweetsuit:1.0

#     # 6. Docker 컨테이너 실행 (GPU 지원)
#     - name: Run Docker container with GPU
#       run: |
#         docker run --gpus all -d -p 8108:8108 ntw0403/sweetsuit:1.0
name: Test, Build, and Deploy API with Local Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    # 자체 호스팅 러너를 사용하도록 설정
    runs-on: [self-hosted, Linux, X64]

    steps:
    # 1. 저장소 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Python 종속성 설치
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.11

    # 3. 모델 파일 디렉토리 연결 (심볼릭 링크 생성)
    - name: Link model directory
      run: |
        mkdir -p api/sweet_suit/removed_bg_model/
        ln -s /mnt/nas4/nto/mustree_sweetsuit/api/sweet_suit/removed_bg_model/lower api/sweet_suit/removed_bg_model/lower
        ln -s /mnt/nas4/nto/mustree_sweetsuit/api/sweet_suit/removed_bg_model/upper api/sweet_suit/removed_bg_model/upper
      shell: bash

    # 4. Python 종속성 설치 및 테스트 실행
    - name: Install dependencies and run tests
      run: |
        pip install poetry
        poetry install --no-root
        poetry run pytest

    # 5. Docker 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Docker 이미지 빌드 (GPU 지원)
    - name: Build Docker Image with Model
      run: |
        docker build --build-arg BASE_IMAGE=nvidia/cuda:12.1.1-base-ubuntu20.04 -t ntw0403/sweetsuit:1.0 .

    # 7. Docker 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push ntw0403/sweetsuit:1.0

    # 8. Docker 컨테이너 실행 (GPU 지원)
    - name: Run Docker container with GPU
      run: |
        docker run --gpus all -d -p 8108:8108 ntw0403/sweetsuit:1.0
