name: Test and Deploy API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Python 종속성 설치 및 테스트 실행
    - name: Set up Python and run tests
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
      run: |
        pip install poetry
        poetry install
        pytest

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ntw0403@naver.com }}
        password: ${{ secrets.shxodnr0403! }}
      run: |
        docker build -t ntw0403@naver.com/sweetsuit:1.0 .
        docker push ntw0403@naver.com/sweetsuit:1.0

    # 4. Docker 컨테이너 실행 (선택 사항)
    - name: Run Docker container locally
      run: |
        docker run -d -p 8108:8108 ntw0403@naver.com/sweetsuit:1.0
